### ISSUE TITLE
error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Shibainu** [fredley/play-pi#18]
Hi,I've just upgraded play-pi after a long interval.
But unfortunately, I'm seeing [Errno 32] Broken pipe when I try to play any music.

Here's the debug info:

    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 55871)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
        self.finish_request(request, client_address)
      File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 150, in __init__
        super(WSGIRequestHandler, self).__init__(*args, **kwargs)
      File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
        self.finish()
      File "/usr/lib/python2.7/SocketServer.py", line 704, in finish
        self.wfile.flush()
      File "/usr/lib/python2.7/socket.py", line 303, in flush
        self._sock.sendall(view[write_offset:write_offset+buffer_size])
    error: [Errno 32] Broken pipe
    ----------------------------------------
    [05/Mar/2015 22:40:51] "GET /ajax/current_song/ HTTP/1.1" 200 91

**Comment by fredley** [comment]
@Shibainu Are you sure mpd is running?

**Comment by Shibainu** [comment]
I think it's running.

    pi@raspberrypi ~/play-pi $ sudo lsof -i:6600
    COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
    mpd     2979  mpd    4u  IPv4   4052      0t0  TCP *:6600 (LISTEN)




    [35;1m[06/Mar/2015 06:38:33] "GET /ajax/current_song/ HTTP/1.1" 500 9949
    [0m[32m[06/Mar/2015 06:38:37] "GET /play/track/1016/ HTTP/1.1" 302 0
    [0mInternal Server Error: /get_stream/1016/
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
    File "/home/pi/play-pi/play_pi/views.py", line 85, in get_stream
    url = get_gplay_url(track.stream_id)
    File "/home/pi/play-pi/play_pi/views.py", line 160, in get_gplay_url
    api.login(GPLAY_USER,GPLAY_PASS)
    File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/webclient.py", line 54, in login
    if not self.session.login(email, password):
    File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 104, in login
    super(Webclient, self).login()
    File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 47, in login
    raise AlreadyLoggedIn
    AlreadyLoggedIn
    [m[06/Mar/2015 06:38:38] "GET /album/180/ HTTP/1.1" 200 8189
    [0mTraceback (most recent call last):
    File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
    File "/usr/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    self.write(data)
    File "/usr/lib/python2.7/wsgiref/handlers.py", line 215, in write
    self._write(data)
    File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
    File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
    error: [Errno 32] Broken pipe
    ----------------------------------------
    Exception happened during processing of request from ('192.168.1.102', 60656)
    Traceback (most recent call last):
    File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
    File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 150, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
    File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
    File "/usr/lib/python2.7/SocketServer.py", line 704, in finish
    self.wfile.flush()
    File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
    error: [Errno 32] Broken pipe

**Comment by fredley** [comment]
Ah ok. I have a fix for this, but I can't push it until this evening!

**Comment by Shibainu** [comment]
Wow! Thanks, fredley!
But there is no hurry.
Thank you for the time and effort!

**Comment by paranoidjack** [comment]
Same problem when using it along with Rune Audio - I can control mpd with play-pi however adding tracks fails with the same error as above.

**Comment by HiroLord** [comment]
I am still getting this issue.

**Comment by fredley** [comment]
This is fixed in 20cc86559190b71e1ada4dc7903e8906039a620b. You'll need to update gmusicapi to the latest version with `pip install --upgrade gmusicapi`. You'll then need to put a `DEVICE_ID` in `local_settings.py`. I'm just about to update the ReadMe with instructions.
