### ISSUE TITLE
lost in the woods

### ISSUE THREAD

**Issue by tedo1960** [fredley/play-pi#24]
probably the wrong place for this but I am struggling.
1. many warnings during extraction and set up.
2. dont get the deice ID requirement - what device do I have to enter and why. I ll be running with touch screen not via mobile device.
3. ./manage.py syncdb just makes a huge mess, loads of stuff on screen and no db created.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 52, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 47, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'play_pi.settings' (Is it on sys.path?): No module named gmusicapi

**Comment by fredley** [comment]
1. This project is quite out of date I'm afraid.
2. You need your device id to authenticate with Google.
3. It looks like you haven't installed gmusicapi, which is a requirement

**Comment by tedo1960** [comment]
Thanks for your help Tom,

Would you recommend I pursue this or look for an alternative. I am trying to use a standalone pi with touch screen as a controller for google play music. This looked a good solution to me.

 

If I do go ahead then it’s the pi ID I need to enter. How do I find this please?

I will try to work out how to find and install gmusicapi.

 

Thanks

 

Ted
