### ISSUE TITLE
AlreadyLoggedIn issue

### ISSUE THREAD

**Issue by emilien81** [fredley/play-pi#38]
I ha ve a issue when I try to read a music.
Below you can find the stacktrace from the server:

[20/Dec/2016 15:35:21] "GET /ajax/current_song/ HTTP/1.1" 200 89
[20/Dec/2016 15:35:21] "GET /get_stream/8043/ HTTP/1.1" 500 74614
- Broken pipe from ('127.0.0.1', 52416)
Internal Server Error: /get_stream/8043/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pi/play-pi/play_pi/views.py", line 85, in get_stream
    url = get_gplay_url(track.stream_id)
  File "/home/pi/play-pi/play_pi/views.py", line 163, in get_gplay_url
    api.login(GPLAY_USER,GPLAY_PASS,DEVICE_ID)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 64, in login
    if not self.session.login(email, password, android_id):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 168, in login
    super(Mobileclient, self).login(email, password, android_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 47, in login
    raise AlreadyLoggedIn
AlreadyLoggedIn

Can you help me ?

Thanks,
Emilien MOREL

**Comment by fredley** [comment]
Fixed in b8a1573cc7fc535abc454928418c37955dd3ea42

**Comment by emilien81** [comment]
I tried your fix but it didn't solved my issue.

Now I have this error (line 167 in views.py file):
[21/Dec/2016 13:45:42] "GET /ajax/current_song/ HTTP/1.1" 200 89
Internal Server Error: /get_stream/8043/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pi/play-pi/play_pi/views.py", line 89, in get_stream
    url = get_gplay_url(track.stream_id)
  File "/home/pi/play-pi/play_pi/views.py", line 167, in get_gplay_url
    api.login(GPLAY_USER,GPLAY_PASS,DEVICE_ID)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 64, in login
    if not self.session.login(email, password, android_id):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 168, in login
    super(Mobileclient, self).login(email, password, android_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 47, in login
    raise AlreadyLoggedIn
AlreadyLoggedIn


Probably I need to configure something I forget.
Do you have an idea ?

Thanks for you help,
Emilien MOREL
