### ISSUE TITLE
Stuck on ./manage.py syncdb

### ISSUE THREAD

**Issue by wtellez1** [fredley/play-pi#6]
Hi, I am VERY beginner trying to setup a Raspberry Pi to play Google music controlled by an Android phone. I copy-pasted your instructions using SSH to myRaspberry but I have got stuck on the instruction ./manage.py syncdb 

It returns the following text (I am very aware that the answer could be pretty obvious, but as i said, I am just a beginner :) I will really appreciate your help to continue):

```
pi@raspberrypi ~/play-pi $ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'play_pi.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named decorator
pi@raspberrypi ~/play-pi $ 
```

**Comment by eagj** [comment]
Hi i have the same problem:
pi@raspberrypi:~/play-pi$ ./manage.py migrateTraceback (most recent call last):  File "./manage.py", line 10, in <module>    execute_from_command_line(sys.argv)  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line    utility.execute()  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute    settings.INSTALLED_APPS  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__    self._setup(name)  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup    self._wrapped = Settings(settings_module)  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__    mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module    __import__(name)  File "/home/pi/play-pi/play_pi/settings.py", line 2, in <module>    from gmusicapi import Webclient  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/__init__.py", line 4, in <module>    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/__init__.py", line 1, in <module>    from gmusicapi.clients.webclient import Webclient  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/webclient.py", line 7, in <module>    from gmusicapi.protocol import webclient  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/webclient.py", line 17, in <module>    from gmusicapi.protocol.shared import Call, authtypes  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 16, in <module>    import requests  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>    from .packages.urllib3.contrib import pyopenssl
File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'pi@raspberrypi:~/play-pi$ sudo ./manage.py migrateTraceback (most recent call last):  File "./manage.py", line 10, in <module>    execute_from_command_line(sys.argv)  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line    utility.execute()  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute    settings.INSTALLED_APPS  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__    self._setup(name)  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup    self._wrapped = Settings(settings_module)  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__    mod = importlib.import_module(self.SETTINGS_MODULE)

And a lot of lines more... i try ro reinstall and the same all time... please help me

**Comment by wtellez1** [comment]
I actually have up since Google launched Chromecast audio. Sorry for not
being helpful.

William

**Comment by eagj** [comment]
Ty Williams, at last i'm another program.
A salute you (i have a chromecast for video)
